import { Metadata } from "next"
import Footer from "./components/footer/Footer"
import Header from "./components/header/Header"

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Learning",
    template: "%s | Leaning",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
